"""Adaptive reflow — abstract algorithm layer.

The framework depends on :class:`SchedulerProtocol`,
:class:`MergeOperatorProtocol`, and :class:`PolicyDriverProtocol`,
not on any single schedule family, merge authority, or per-round
restart philosophy. :class:`CosineAnnealScheduler`,
:class:`BoundedMergeOperator`, and :class:`ScheduleDerivedPolicyDriver`
are the default implementations; linear ramp, exponential decay, and
constant schedules can be substituted by conforming to the same
Protocol; constant-``beta`` and adaptive ``beta`` drivers can be
substituted via :class:`PolicyDriverProtocol`.

Wave 105 P2-C note
==================

The algorithm top-level was grouped into 4 subpackages
(:mod:`adaptive_reflow.algorithm.runner`,
:mod:`adaptive_reflow.algorithm.blender`,
:mod:`adaptive_reflow.algorithm.merge`,
:mod:`adaptive_reflow.algorithm.perturbation`) on 2026-09-11.
The historical top-level module paths (``adaptive_reflow.algorithm.batched_runner``,
``adaptive_reflow.algorithm.blender``, …) are preserved as thin
re-export shims; this :mod:`__init__` continues to expose the full
public surface, but now sources each symbol from its canonical
subpackage path.
"""
from .batched_runner import (
    BatchedRunnerConfig,
    BatchedTrajectoryResult,
    BatchedTrajectoryRunner,
)
from .blender import (
    DEFAULT_DISTANCE_DECAY_CONFIG_HASH,
    DEFAULT_DISTANCE_DECAY_TEMPERATURE,
    DEFAULT_LINEAR_CONFIG_HASH,
    DISTANCE_DECAY_FAMILY,
    LINEAR_FAMILY,
    DistanceDecayBlender,
    LinearBlender,
    RestartBlenderProtocol,
    default_blender,
)
from .blender_extra import (
    MultiTemperatureDistanceDecayBlender,
    OTLinearBlender,
)
from .categorical_blender import (
    CATEGORICAL_AWARE_FAMILY,
    CATEGORICAL_BLEND_MASK_FRESH_FALLBACK,
    CATEGORICAL_BLEND_SENTINEL_PASSTHROUGH,
    CATEGORICAL_BLEND_TAU_FLOOR_HIT,
    CategoricalAwareBlender,
    DEFAULT_CATEGORICAL_AWARE_CONFIG_HASH,
    DEFAULT_TAU_FLOOR,
    DEFAULT_TAU_SCHEDULE_KIND,
    default_categorical_blender,
)
from .dynamic_noise_bias import (
    CategoricalDynamicNoiseBias,
    DEFAULT_DECAY_KIND,
    DEFAULT_MIN_GUMBEL_TEMP,
    DynamicNoiseBiasProtocol,
    IdentityDynamicNoiseBias,
    NEW_DYNAMIC_NOISE_BIAS_COMPUTED,
    NEW_DYNAMIC_NOISE_BIAS_DIGEST_ONLY,
    NEW_DYNAMIC_NOISE_BIAS_EPSILON_FLOORED_BY_PAPER_EXTERIOR_GAP,
    NEW_DYNAMIC_NOISE_BIAS_EPSILON_NONPOSITIVE,
    NEW_DYNAMIC_NOISE_BIAS_GUMBEL_HEURISTIC,
    NEW_DYNAMIC_NOISE_BIAS_GUMBEL_TEMP_COMPUTED,
    NEW_DYNAMIC_NOISE_BIAS_NO_MATERIALIZER,
    NEW_DYNAMIC_NOISE_BIAS_PREV_ANCHORED_TO_PREV_ENDPOINT,
    NEW_DYNAMIC_NOISE_BIAS_SHEET_NONPOSITIVE,
    Theorem1DynamicNoiseBias,
    default_dynamic_noise_bias,
)
from .dynamics import (
    BFN_FAMILY,
    CONTINUOUS_FM_FAMILY,
    CTMC_FAMILY,
    DEFAULT_BFN_CONFIG_HASH,
    DEFAULT_CONTINUOUS_FM_CONFIG_HASH,
    DEFAULT_CTMC_CONFIG_HASH,
    BFNDynamics,
    ContinuousFMDynamics,
    CTMCDynamics,
    DynamicsProtocol,
    DynamicsTrajectory,
    EXTERIOR_GAP_FLOOR_FRACTION,
    FlowMol3Dynamics,
    ProtBFNDynamics,
    default_bfn_dynamics,
    default_continuous_fm_dynamics,
    default_ctmc_dynamics,
)
from .solver import (
    ADAPTIVE_RK4_FAMILY,
    BFN_FAMILY as SOLVER_BFN_FAMILY,
    CTMC_EULER_HEUN_FAMILY,
    DEFAULT_ADAPTIVE_RK4_CONFIG_HASH,
    DEFAULT_BFN_CONFIG_HASH as DEFAULT_SOLVER_BFN_CONFIG_HASH,
    DEFAULT_CTMC_EULER_HEUN_CONFIG_HASH,
    DEFAULT_EULER_CONFIG_HASH,
    DEFAULT_HEUN_CONFIG_HASH,
    DEFAULT_RK4_CONFIG_HASH,
    EULER_FAMILY,
    HEUN_FAMILY,
    RK4_FAMILY,
    AdaptiveRK4Solver,
    BFNSolver,
    CTMCEulerHeunSolver,
    EulerSolver,
    HeunSolver,
    IntegratorProtocol,
    RK4Solver,
    build_solver_from_config,
    default_ctmc_euler_heun_solver,
    default_euler_solver,
    default_heun_solver,
    default_rk4_solver,
)
from .merge_operator import (
    ERR_PREV_REQUIRED,
    MERGE_CAP_OUT_OF_RANGE,
    MERGE_DEGENERATE_INTERVAL,
    MERGE_FLOOR_FALLBACK,
    MERGE_FLOOR_OUT_OF_RANGE,
    MERGE_NONFINITE_DYNAMIC_CLIPPED,
    MERGE_NONFINITE_PREV_CLIPPED,
    MERGE_PREV_ANCHORED_TO_LAST_EMITTED,
    BoundedMergeOperator,
    EMAOperator,
    IdentityOperator,
    MergeAuthorityError,
    MergeOperatorProtocol,
    default_bounded_merge_operator,
)
from .per_channel_blender import (
    BLEND_FAMILY_BY_CHANNEL,
    DEFAULT_BLEND_FAMILY_BY_CHANNEL,
    DEFAULT_TAU_DEFAULT,
    DEFAULT_TAU_FLOOR,
    EPS_LOG,
    GUMBEL_FAMILY,
    GRAPH_FAMILY,
    GumbelBlend,
    LINEAR_FAMILY,
    LinearBlend,
    LOGIT_FAMILY,
    LogitBlend,
    MASKED_FAMILY,
    MaskedBlend,
    PER_CHANNEL_BLEND_FALLTHROUGH,
    PER_CHANNEL_BLEND_MASK_FRESH_FALLBACK,
    PER_CHANNEL_BLEND_M_ONE_SHORTCIRCUIT,
    PER_CHANNEL_BLEND_M_ZERO_SHORTCIRCUIT,
    PER_CHANNEL_BLEND_SENTINEL_PASSTHROUGH,
    PER_CHANNEL_BLEND_TAU_FLOOR_HIT,
    PerChannelBlender,
    BlendStrategy,
    SAMPLE_FAMILY,
    SampleBlend,
    GraphBlend,
    default_per_channel_blender,
)
from .merge_operator_extra import (
    BayesianMergeOperator,
    KalmanBoundedMergeOperator,
    PIDIdentityOperator,
    ScheduleAwareEMAOperator,
)
from .policy_driver import (
    ADAPTIVE_FAMILY,
    CONSTANT_FAMILY,
    DEFAULT_ADAPTIVE_TARGET_ESTIMATE,
    DEFAULT_CONSTANT_BETA,
    SCHEDULE_DERIVED_FAMILY,
    AdaptivePolicyDriver,
    ConstantPolicyDriver,
    PolicyDriverProtocol,
    ScheduleDerivedPolicyDriver,
    default_policy_driver,
)
from .protocol_registry import (
    BLENDER_FAMILIES,
    DYNAMICS_FAMILIES,
    MERGE_OPERATOR_FAMILIES,
    POLICY_DRIVER_FAMILIES,
    PROTOCOL_REGISTRY,
    SCHEDULER_FAMILIES,
    SOLVER_FAMILIES,
    ProtocolRegistryError,
    build_blender_from_config,
    build_dynamics_from_config,
    build_merge_operator_from_config,
    build_policy_driver_from_config,
    build_scheduler_from_config,
    build_solver_from_config,
    enumerate_implementations,
    registered_families,
    validate_config_schema,
)
from .rotation_policy import (
    ROTATION_POLICY_REGISTRY,
    BanditUCBRotationPolicy,
    RotationPolicy,
    RoundRobinRotationPolicy,
    build_rotation_policy,
)
from .runner import (
    FORWARD_NOISE_INJECTED,
    ReInferenceConfig,
    ReInferenceResult,
    ReInferenceRunner,
)
from .runner_registry import (
    RUNNER_REGISTRY,
    BatchedTrajectoryRunnerFamily,
    EarlyStopRunner,
    OnlineRunner,
    ParallelRunner,
    ReInferenceRunnerFamily,
    RunnerProtocol,
    build_runner,
)
from .scheduler import (
    SCHEDULER_REGISTRY,
    CodimensionSheetScheduler,
    ConstantScheduler,
    ConvergenceAdaptiveScheduler,
    CosineAnnealScheduler,
    DEFAULT_NFE_AWARE_MAX,
    DEFAULT_NFE_AWARE_THRESHOLD,
    ExponentialScheduler,
    LinearScheduler,
    NFEAwareMemoryScheduler,
    PaperRatioAdaptiveScheduler,
    PolynomialScheduler,
    SchedulerProtocol,
    ScheduleSample,
    ScheduleSampleProtocol,
    SigmoidScheduler,
    build_scheduler,
    default_cosine_scheduler,
    default_paper_ratio_scheduler,
)
from .scheduler_extra import (
    EDM_RHO_DEFAULT,
    EDM_SIGMA_MAX_DEFAULT,
    EDM_SIGMA_MIN_DEFAULT,
    AdaptivePIDScheduler,
    EDMScheduler,
    JitteredConstantScheduler,
)
from .sequential import (
    SEQUENTIAL_FAMILY,
    SequentialScheduler,
    SequentialSlot,
)

__all__ = [
    "ADAPTIVE_FAMILY",
    "AdaptivePIDScheduler",
    "AdaptivePolicyDriver",
    "BatchedRunnerConfig",
    "BatchedTrajectoryResult",
    "BatchedTrajectoryRunner",
    "BatchedTrajectoryRunnerFamily",
    "BayesianMergeOperator",
    "BLEND_FAMILY_BY_CHANNEL",
    "BLENDER_FAMILIES",
    "BoundedMergeOperator",
    "CATEGORICAL_AWARE_FAMILY",
    "CATEGORICAL_BLEND_MASK_FRESH_FALLBACK",
    "CATEGORICAL_BLEND_SENTINEL_PASSTHROUGH",
    "CATEGORICAL_BLEND_TAU_FLOOR_HIT",
    "CategoricalAwareBlender",
    "CategoricalDynamicNoiseBias",
    "CONSTANT_FAMILY",
    "CodimensionSheetScheduler",
    "ConstantPolicyDriver",
    "ConstantScheduler",
    "ConvergenceAdaptiveScheduler",
    "CosineAnnealScheduler",
    "DEFAULT_ADAPTIVE_TARGET_ESTIMATE",
    "DEFAULT_BLEND_FAMILY_BY_CHANNEL",
    "DEFAULT_CATEGORICAL_AWARE_CONFIG_HASH",
    "DEFAULT_CONSTANT_BETA",
    "DEFAULT_DECAY_KIND",
    "DEFAULT_DISTANCE_DECAY_CONFIG_HASH",
    "DEFAULT_DISTANCE_DECAY_TEMPERATURE",
    "DEFAULT_LINEAR_CONFIG_HASH",
    "DEFAULT_MIN_GUMBEL_TEMP",
    "DEFAULT_NFE_AWARE_MAX",
    "DEFAULT_NFE_AWARE_THRESHOLD",
    "DEFAULT_TAU_DEFAULT",
    "DEFAULT_TAU_FLOOR",
    "DEFAULT_TAU_SCHEDULE_KIND",
    "DISTANCE_DECAY_FAMILY",
    "DistanceDecayBlender",
    "DynamicNoiseBiasProtocol",
    "EDM_RHO_DEFAULT",
    "EDM_SIGMA_MAX_DEFAULT",
    "EDM_SIGMA_MIN_DEFAULT",
    "EDMScheduler",
    "EMAOperator",
    "EarlyStopRunner",
    "FORWARD_NOISE_INJECTED",
    "ERR_PREV_REQUIRED",
    "ExponentialScheduler",
    "IdentityDynamicNoiseBias",
    "IdentityOperator",
    "JitteredConstantScheduler",
    "KalmanBoundedMergeOperator",
    "LINEAR_FAMILY",
    "LinearBlender",
    "LinearScheduler",
    "LOGIT_FAMILY",
    "LogitBlend",
    "MASKED_FAMILY",
    "PaperRatioAdaptiveScheduler",
    "MaskedBlend",
    "MERGE_CAP_OUT_OF_RANGE",
    "MERGE_DEGENERATE_INTERVAL",
    "MERGE_FLOOR_FALLBACK",
    "MERGE_FLOOR_OUT_OF_RANGE",
    "MERGE_NONFINITE_DYNAMIC_CLIPPED",
    "MERGE_NONFINITE_PREV_CLIPPED",
    "MERGE_PREV_ANCHORED_TO_LAST_EMITTED",
    "MERGE_OPERATOR_FAMILIES",
    "MergeAuthorityError",
    "MergeOperatorProtocol",
    "MultiTemperatureDistanceDecayBlender",
    "NEW_DYNAMIC_NOISE_BIAS_COMPUTED",
    "NEW_DYNAMIC_NOISE_BIAS_DIGEST_ONLY",
    "NFEAwareMemoryScheduler",
    "NEW_DYNAMIC_NOISE_BIAS_EPSILON_FLOORED_BY_PAPER_EXTERIOR_GAP",
    "NEW_DYNAMIC_NOISE_BIAS_EPSILON_NONPOSITIVE",
    "NEW_DYNAMIC_NOISE_BIAS_GUMBEL_HEURISTIC",
    "NEW_DYNAMIC_NOISE_BIAS_GUMBEL_TEMP_COMPUTED",
    "NEW_DYNAMIC_NOISE_BIAS_NO_MATERIALIZER",
    "NEW_DYNAMIC_NOISE_BIAS_PREV_ANCHORED_TO_PREV_ENDPOINT",
    "NEW_DYNAMIC_NOISE_BIAS_SHEET_NONPOSITIVE",
    "OTLinearBlender",
    "OnlineRunner",
    "PIDIdentityOperator",
    "POLICY_DRIVER_FAMILIES",
    "PROTOCOL_REGISTRY",
    "ParallelRunner",
    "PER_CHANNEL_BLEND_FALLTHROUGH",
    "PER_CHANNEL_BLEND_MASK_FRESH_FALLBACK",
    "PER_CHANNEL_BLEND_M_ONE_SHORTCIRCUIT",
    "PER_CHANNEL_BLEND_M_ZERO_SHORTCIRCUIT",
    "PER_CHANNEL_BLEND_SENTINEL_PASSTHROUGH",
    "PER_CHANNEL_BLEND_TAU_FLOOR_HIT",
    "PerChannelBlender",
    "BlendStrategy",
    "PolicyDriverProtocol",
    "PolynomialScheduler",
    "ProtocolRegistryError",
    "ROTATION_POLICY_REGISTRY",
    "ReInferenceRunnerFamily",
    "RestartBlenderProtocol",
    "ReInferenceConfig",
    "ReInferenceResult",
    "ReInferenceRunner",
    "RotationPolicy",
    "RoundRobinRotationPolicy",
    "RUNNER_REGISTRY",
    "RunnerProtocol",
    "SAMPLE_FAMILY",
    "SampleBlend",
    "GraphBlend",
    "SCHEDULER_FAMILIES",
    "SCHEDULER_REGISTRY",
    "SCHEDULE_DERIVED_FAMILY",
    "ScheduleAwareEMAOperator",
    "ScheduleDerivedPolicyDriver",
    "ScheduleSample",
    "ScheduleSampleProtocol",
    "SchedulerProtocol",
    "SequentialScheduler",
    "SequentialSlot",
    "SigmoidScheduler",
    "BanditUCBRotationPolicy",
    "Theorem1DynamicNoiseBias",
    "AdaptiveRK4Solver",
    "BFNDynamics",
    "BFNSolver",
    "CTMCEulerHeunSolver",
    "CTMCDynamics",
    "ContinuousFMDynamics",
    "DynamicsProtocol",
    "DynamicsTrajectory",
    "EulerSolver",
    "FlowMol3Dynamics",
    "HeunSolver",
    "IntegratorProtocol",
    "ProtBFNDynamics",
    "RK4Solver",
    "build_blender_from_config",
    "build_dynamics_from_config",
    "build_merge_operator_from_config",
    "build_policy_driver_from_config",
    "build_rotation_policy",
    "build_runner",
    "build_scheduler",
    "build_scheduler_from_config",
    "build_solver_from_config",
    "default_bfn_dynamics",
    "default_blender",
    "default_bounded_merge_operator",
    "default_categorical_blender",
    "default_continuous_fm_dynamics",
    "default_codimension_sheet_scheduler",
    "default_cosine_scheduler",
    "default_paper_ratio_scheduler",
    "default_ctmc_dynamics",
    "default_ctmc_euler_heun_solver",
    "default_dynamic_noise_bias",
    "default_euler_solver",
    "default_heun_solver",
    "default_per_channel_blender",
    "default_policy_driver",
    "default_rk4_solver",
    "enumerate_implementations",
    "registered_families",
    "validate_config_schema",
]
