"""Adaptive reflow — abstract algorithm layer.

The framework depends on :class:`SchedulerProtocol`,
:class:`MergeOperatorProtocol`, and :class:`PolicyDriverProtocol`,
not on any single schedule family, merge authority, or per-round
restart philosophy. :class:`CosineAnnealScheduler`,
:class:`BoundedMergeOperator`, and :class:`ScheduleDerivedPolicyDriver`
are the default implementations; linear ramp, exponential decay, and
constant schedules can be substituted by conforming to the same
Protocol; constant-``beta`` and adaptive ``beta`` drivers can be
substituted via :class:`PolicyDriverProtocol`.
"""
from .batched_runner import (
    BatchedRunnerConfig,
    BatchedTrajectoryResult,
    BatchedTrajectoryRunner,
)
from .blender import (
    DEFAULT_DISTANCE_DECAY_CONFIG_HASH,
    DEFAULT_DISTANCE_DECAY_TEMPERATURE,
    DEFAULT_LINEAR_CONFIG_HASH,
    DISTANCE_DECAY_FAMILY,
    LINEAR_FAMILY,
    DistanceDecayBlender,
    LinearBlender,
    RestartBlenderProtocol,
    default_blender,
)
from .blender_extra import (
    MultiTemperatureDistanceDecayBlender,
    OTLinearBlender,
)
from .merge_operator import (
    ERR_PREV_REQUIRED,
    MERGE_CAP_OUT_OF_RANGE,
    MERGE_DEGENERATE_INTERVAL,
    MERGE_FLOOR_FALLBACK,
    MERGE_FLOOR_OUT_OF_RANGE,
    MERGE_NONFINITE_DYNAMIC_CLIPPED,
    MERGE_NONFINITE_PREV_CLIPPED,
    MERGE_PREV_ANCHORED_TO_LAST_EMITTED,
    BoundedMergeOperator,
    EMAOperator,
    IdentityOperator,
    MergeAuthorityError,
    MergeOperatorProtocol,
    default_bounded_merge_operator,
)
from .merge_operator_extra import (
    BayesianMergeOperator,
    KalmanBoundedMergeOperator,
    PIDIdentityOperator,
    ScheduleAwareEMAOperator,
)
from .policy_driver import (
    ADAPTIVE_FAMILY,
    CONSTANT_FAMILY,
    DEFAULT_ADAPTIVE_TARGET_ESTIMATE,
    DEFAULT_CONSTANT_BETA,
    SCHEDULE_DERIVED_FAMILY,
    AdaptivePolicyDriver,
    ConstantPolicyDriver,
    PolicyDriverProtocol,
    ScheduleDerivedPolicyDriver,
    default_policy_driver,
)
from .protocol_registry import (
    BLENDER_FAMILIES,
    MERGE_OPERATOR_FAMILIES,
    POLICY_DRIVER_FAMILIES,
    PROTOCOL_REGISTRY,
    SCHEDULER_FAMILIES,
    ProtocolRegistryError,
    build_blender_from_config,
    build_merge_operator_from_config,
    build_policy_driver_from_config,
    build_scheduler_from_config,
    enumerate_implementations,
    registered_families,
    validate_config_schema,
)
from .rotation_policy import (
    ROTATION_POLICY_REGISTRY,
    BanditUCBRotationPolicy,
    RotationPolicy,
    RoundRobinRotationPolicy,
    build_rotation_policy,
)
from .runner import (
    FORWARD_NOISE_INJECTED,
    ReInferenceConfig,
    ReInferenceResult,
    ReInferenceRunner,
)
from .runner_registry import (
    RUNNER_REGISTRY,
    BatchedTrajectoryRunnerFamily,
    EarlyStopRunner,
    OnlineRunner,
    ParallelRunner,
    ReInferenceRunnerFamily,
    RunnerProtocol,
    build_runner,
)
from .scheduler import (
    SCHEDULER_REGISTRY,
    CodimensionSheetScheduler,
    ConstantScheduler,
    ConvergenceAdaptiveScheduler,
    CosineAnnealScheduler,
    ExponentialScheduler,
    LinearScheduler,
    PolynomialScheduler,
    SchedulerProtocol,
    ScheduleSample,
    ScheduleSampleProtocol,
    SigmoidScheduler,
    build_scheduler,
    default_cosine_scheduler,
)
from .scheduler_extra import (
    EDM_RHO_DEFAULT,
    EDM_SIGMA_MAX_DEFAULT,
    EDM_SIGMA_MIN_DEFAULT,
    AdaptivePIDScheduler,
    EDMScheduler,
    JitteredConstantScheduler,
)
from .sequential import (
    SEQUENTIAL_FAMILY,
    SequentialScheduler,
    SequentialSlot,
)

__all__ = [
    "ADAPTIVE_FAMILY",
    "AdaptivePIDScheduler",
    "AdaptivePolicyDriver",
    "BatchedRunnerConfig",
    "BatchedTrajectoryResult",
    "BatchedTrajectoryRunner",
    "BatchedTrajectoryRunnerFamily",
    "BayesianMergeOperator",
    "BLENDER_FAMILIES",
    "BoundedMergeOperator",
    "CONSTANT_FAMILY",
    "CodimensionSheetScheduler",
    "ConstantPolicyDriver",
    "ConstantScheduler",
    "ConvergenceAdaptiveScheduler",
    "CosineAnnealScheduler",
    "DEFAULT_ADAPTIVE_TARGET_ESTIMATE",
    "DEFAULT_CONSTANT_BETA",
    "DEFAULT_DISTANCE_DECAY_CONFIG_HASH",
    "DEFAULT_DISTANCE_DECAY_TEMPERATURE",
    "DEFAULT_LINEAR_CONFIG_HASH",
    "DISTANCE_DECAY_FAMILY",
    "DistanceDecayBlender",
    "EDM_RHO_DEFAULT",
    "EDM_SIGMA_MAX_DEFAULT",
    "EDM_SIGMA_MIN_DEFAULT",
    "EDMScheduler",
    "EMAOperator",
    "EarlyStopRunner",
    "FORWARD_NOISE_INJECTED",
    "ERR_PREV_REQUIRED",
    "ExponentialScheduler",
    "IdentityOperator",
    "JitteredConstantScheduler",
    "KalmanBoundedMergeOperator",
    "LINEAR_FAMILY",
    "LinearBlender",
    "LinearScheduler",
    "MERGE_CAP_OUT_OF_RANGE",
    "MERGE_DEGENERATE_INTERVAL",
    "MERGE_FLOOR_FALLBACK",
    "MERGE_FLOOR_OUT_OF_RANGE",
    "MERGE_NONFINITE_DYNAMIC_CLIPPED",
    "MERGE_NONFINITE_PREV_CLIPPED",
    "MERGE_PREV_ANCHORED_TO_LAST_EMITTED",
    "MERGE_OPERATOR_FAMILIES",
    "MergeAuthorityError",
    "MergeOperatorProtocol",
    "MultiTemperatureDistanceDecayBlender",
    "OTLinearBlender",
    "OnlineRunner",
    "PIDIdentityOperator",
    "POLICY_DRIVER_FAMILIES",
    "PROTOCOL_REGISTRY",
    "ParallelRunner",
    "PolicyDriverProtocol",
    "PolynomialScheduler",
    "ProtocolRegistryError",
    "ROTATION_POLICY_REGISTRY",
    "ReInferenceRunnerFamily",
    "RestartBlenderProtocol",
    "ReInferenceConfig",
    "ReInferenceResult",
    "ReInferenceRunner",
    "RotationPolicy",
    "RoundRobinRotationPolicy",
    "RUNNER_REGISTRY",
    "RunnerProtocol",
    "SCHEDULER_FAMILIES",
    "SCHEDULER_REGISTRY",
    "SCHEDULE_DERIVED_FAMILY",
    "ScheduleAwareEMAOperator",
    "ScheduleDerivedPolicyDriver",
    "ScheduleSample",
    "ScheduleSampleProtocol",
    "SchedulerProtocol",
    "SequentialScheduler",
    "SequentialSlot",
    "SigmoidScheduler",
    "BanditUCBRotationPolicy",
    "build_blender_from_config",
    "build_merge_operator_from_config",
    "build_policy_driver_from_config",
    "build_rotation_policy",
    "build_runner",
    "build_scheduler",
    "build_scheduler_from_config",
    "default_blender",
    "default_bounded_merge_operator",
    "default_cosine_scheduler",
    "default_policy_driver",
    "enumerate_implementations",
    "registered_families",
    "validate_config_schema",
]
